/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgentGatewaySettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "owner"
      | "payments"
      | "platformBalances"
      | "platformFeeRecipient"
      | "providerBalances"
      | "recordPayment"
      | "registerAgent"
      | "setPlatformFeeRecipient"
      | "updateAgent"
      | "withdrawPlatform"
      | "withdrawProvider"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentUpdated"
      | "PaymentRecorded"
      | "PlatformWithdrawn"
      | "ProviderWithdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "payments", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "platformBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerBalances",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPayment",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [BytesLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatform",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProvider",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatform",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProvider",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BytesLike,
    provider: AddressLike,
    token: AddressLike,
    feeBps: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    provider: string,
    token: string,
    feeBps: bigint
  ];
  export interface OutputObject {
    agentId: string;
    provider: string;
    token: string;
    feeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    provider: AddressLike,
    token: AddressLike,
    feeBps: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    agentId: string,
    provider: string,
    token: string,
    feeBps: bigint,
    active: boolean
  ];
  export interface OutputObject {
    agentId: string;
    provider: string;
    token: string;
    feeBps: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRecordedEvent {
  export type InputTuple = [
    usageId: BytesLike,
    agentId: BytesLike,
    user: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    usageId: string,
    agentId: string,
    user: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    usageId: string;
    agentId: string;
    user: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformWithdrawnEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderWithdrawnEvent {
  export type InputTuple = [
    agentId: BytesLike,
    provider: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    provider: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    agentId: string;
    provider: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentGatewaySettlement extends BaseContract {
  connect(runner?: ContractRunner | null): AgentGatewaySettlement;
  waitForDeployment(): Promise<this>;

  interface: AgentGatewaySettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        provider: string;
        token: string;
        feeBps: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  platformBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  platformFeeRecipient: TypedContractMethod<[], [string], "view">;

  providerBalances: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  recordPayment: TypedContractMethod<
    [
      agentId: BytesLike,
      user: AddressLike,
      amount: BigNumberish,
      usageId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFeeRecipient: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgent: TypedContractMethod<
    [
      agentId: BytesLike,
      token: AddressLike,
      feeBps: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  withdrawPlatform: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawProvider: TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        provider: string;
        token: string;
        feeBps: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providerBalances"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordPayment"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      user: AddressLike,
      amount: BigNumberish,
      usageId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFeeRecipient"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      token: AddressLike,
      feeBps: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawPlatform"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawProvider"
  ): TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRecorded"
  ): TypedContractEvent<
    PaymentRecordedEvent.InputTuple,
    PaymentRecordedEvent.OutputTuple,
    PaymentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformWithdrawn"
  ): TypedContractEvent<
    PlatformWithdrawnEvent.InputTuple,
    PlatformWithdrawnEvent.OutputTuple,
    PlatformWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ProviderWithdrawn"
  ): TypedContractEvent<
    ProviderWithdrawnEvent.InputTuple,
    ProviderWithdrawnEvent.OutputTuple,
    ProviderWithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(bytes32,address,address,uint96)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(bytes32,address,address,uint96,bool)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "PaymentRecorded(bytes32,bytes32,address,uint256,address)": TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;
    PaymentRecorded: TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;

    "PlatformWithdrawn(address,uint256)": TypedContractEvent<
      PlatformWithdrawnEvent.InputTuple,
      PlatformWithdrawnEvent.OutputTuple,
      PlatformWithdrawnEvent.OutputObject
    >;
    PlatformWithdrawn: TypedContractEvent<
      PlatformWithdrawnEvent.InputTuple,
      PlatformWithdrawnEvent.OutputTuple,
      PlatformWithdrawnEvent.OutputObject
    >;

    "ProviderWithdrawn(bytes32,address,address,uint256)": TypedContractEvent<
      ProviderWithdrawnEvent.InputTuple,
      ProviderWithdrawnEvent.OutputTuple,
      ProviderWithdrawnEvent.OutputObject
    >;
    ProviderWithdrawn: TypedContractEvent<
      ProviderWithdrawnEvent.InputTuple,
      ProviderWithdrawnEvent.OutputTuple,
      ProviderWithdrawnEvent.OutputObject
    >;
  };
}
